FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy only the requirements file to leverage Docker cache
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire API directory to the container
COPY . /app

# Expose the Flask API port
EXPOSE 5002

# Run the Flask API
CMD ["python", "src/api.py"]
