version: '3.11'

services:
  flask_api:
    build:
      context: .
      dockerfile: dockerfile.api
    ports:
      - "5002:5002"
    network_mode: bridge

  streamlit_app:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "8501:8501"
    depends_on:
      - flask_api
    network_mode: bridge
