FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy only the requirements file to leverage Docker cache
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire Web app directory to the container
COPY . /app

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "src/web.py", "--server.port=8501"]
